project_name: golang-training

before:
  hooks:
    - rm -rf dist
    - go mod tidy
    - git push
    - git push --tags

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X golang-training/version.Version=v{{.Version}}

snapshot:
  name_template: "{{ incminor .Version }}-dev"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/saimonwoidig/golang-training:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    ids:
      - golang-training
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/SaimonWoidig/golang-training"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=repository=https://github.com/SaimonWoidig/golang-training"
      - "--label=maintainer=SimonWoidig <woidig.simon@gmail.com>"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
